variable rg           {}
variable mgmt_subnet  {}
variable data_subnet  {}
variable nsg          {}
variable lb_pool      {}
variable bigip_count  {}
variable bigip        {}
variable f5_common    {}
variable bigiq_host   {}
variable bigiq        {}
variable analytics    {}
variable law          {}
#variable uai          {}
